### ISSUE TITLE
File Not Found for civilcomments train

### ISSUE THREAD

**Issue by pratyushmaini** [facebookresearch/BalancingGroups#2]
Are you using a different file for train set? It does not seem to get automatically downloaded.

FileNotFoundError: [Errno 2] No such file or directory: 'tr/civilcomments/civilcomments_fine.csv'

----
  File "train.py", line 57, in run_experiment
    loaders = get_loaders(args["data_path"], args["dataset"], args["batch_size"], args["method"])
  File "datasets.py", line 347, in get_loaders
    dataset_tr = Dataset(data_path, "tr", subsample_what, duplicates)
  File "datasets.py", line 235, in __init__
    super().__init__(split, data_path, subsample_what, duplicates, "fine")
  File "datasets.py", line 195, in __init__
    text = pd.read_csv(

**Comment by BadrYoubiIdrissi** [comment]
Hello Pratyush,

Thank you for your interest in our paper. 

Has the setup_datasets.py script described in the readme finished running without any errors on your side? I have just relaunched it on my part and the file you're describing exists for me.

**Comment by pratyushmaini** [comment]
To be sure, I deleted the data folder and run the download script as in the README again. But I still get the same error for civilcomments, and the file is not downloaded

**Comment by BadrYoubiIdrissi** [comment]
I just figured out the error, the constructor of the CivilCommentsFine class was sending arguments in the wrong order to its parent. The bug has been introduced during clean up of the code. It has now been fixed and pushed to main. 

Sorry for the inconvenience ! You should be able to relaunch training now. (No need to redownload. There is no specific file for civilcomments training)

Let me know if you encounter any more problems.
